<MyLayout>
	BoxLayout:
		orientation: 'vertical'
		size: root.width, root.height

		Label:
			# 使用 markup
			markup: True

			font_size: 32
			text: "This is [color=#a12c3c][b]Bold[/b][/color] Text [sup]Up[/sup] and [sub]Down[/sub]"


		Label:
			markup: True
			font_size: 32
			text: "This is [size=150][i]Italics[/i][/size] [font=times]Text[/font]"

		Button:
			markup: True
			font_size: 32
			text: "[u]Click[/u] [s]Me![/s]"

